name: task_reminder_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1  # Add this for Firestore
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  audioplayers: ^6.5.1  # Use the latest version as of April 2025
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  window_manager: ^0.5.1
  system_tray: ^2.0.3
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/app_icon.ico
    - assets/sounds/notification.mp3
    - assets/sounds/chime.mp3
    - assets/sounds/beep.mp3

  fonts:
    - family: NotoSansLao
      fonts:
        - asset: fonts/NotoSansLao-Regular.ttf