name: task_reminder_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4  # Add this for Firestore
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  audioplayers: ^5.2.1  # Use the latest version as of April 2025


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/sounds/notification.mp3  # Adjust the filen

  fonts:
    - family: NotoSansLao
      fonts:
        - asset: fonts/NotoSansLao-Regular.ttf